on: [push]

jobs:
  az-login:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@master
      with:
        creds: {{SECRETS.AZURE_CREDENTIALS}}
      id: login
    - run: echo "Filler output"